/**
 * db/build-db.js
 * ───────────────
 * Loads and queries the static game data files in db/data/.
 * Generated by extractor/extract.py. Re-run extractor after each game patch.
 *
 * ─── Data Files ──────────────────────────────────────────────────────────────
 *
 *  db/data/skill_tree_reconciled.json → flat array of all passive + skill nodes
 *                                       Generated by extractor/extract.py.
 *                                       Name resolution improves as reconciliation work matures.
 *  db/data/classes.json               → { classes, masteries, passiveTreeByClass }
 *
 * ─── Node shape (from skill_tree_reconciled.json) ────────────────────────────
 * {
 *   treeID:      string,   — tree identifier; equals Maxroll skillKey for skills
 *   treeName:    string,   — human-readable tree/skill name
 *   nodeID:      number,   — node identifier used in Maxroll history[]
 *   nodeName:    string,   — player-facing display name
 *   description: string,   — in-game tooltip text
 *   maxPoints:   number,   — max allocatable points (0 = root/connector)
 *   stats:       array,    — [{ statName, value }] per-point effects
 * }
 *
 * ─── Passive tree structure ───────────────────────────────────────────────────
 *
 *  Passive trees are included in skill_tree_reconciled.json alongside skill trees.
 *  They use the same treeID convention (e.g. "kn-1" for Sentinel/Knight).
 *
 *  To look up a passive node you need classId → treeID → nodeId:
 *    db.getPassive(classId, nodeId)
 *
 *  classId → treeID mapping (from classes.json passiveTreeByClass):
 *    1 (Acolyte)   → "ac-1"
 *    2 (Mage)      → "mg-1"
 *    3 (Sentinel)  → "kn-1"
 *    4 (Rogue)     → "rg-1"
 *    5 (Primalist) → "pr-1"
 *
 * ─── treeID = Maxroll skillKey ───────────────────────────────────────────────
 *
 *  Skills are keyed by treeID which is the exact same key Maxroll uses.
 *  e.g. trees["es6ai"] = Erasing Strike, trees["v01cv"] = Void Cleave.
 *  No mapping step is needed.
 *
 * ─── Usage ───────────────────────────────────────────────────────────────────
 *
 *   const db = require('./build-db');
 *   db.load();
 *
 *   db.getPassive(3, 49)           // classId=3 (Sentinel), nodeId=49 → node | null
 *   db.getSkillNode('es6ai', 2)    // skillKey, nodeId → node | null
 *   db.getSkillName('es6ai')       // → "Erasing Strike" | null
 *   db.getPassiveTreeId(3)         // classId → "kn-1"
 *   db.getClassName(3)             // → "Sentinel" | null
 *   db.getMasteryName(3, 2)         // → "Void Knight" | null  (classId, per-class masteryId)
 *   db.all()                       // → { passives, skills, classes }
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');

// ─── Internal state ───────────────────────────────────────────────────────────

// Unified tree map covering both passives and skills.
// Both _passives and _skills reference the same object — queries work identically.
let _trees   = {};   // { [treeID]: { name, nodes: { [id]: node } } }
let _passives = _trees;
let _skills   = _trees;
let _classes  = { classes: {}, masteries: {}, passiveTreeByClass: {} };
let _loaded   = false;

// ─── Loader ───────────────────────────────────────────────────────────────────

/**
 * Load all data files into memory. Safe to call multiple times.
 * @param {boolean} [force=false]
 */
function load(force = false) {
  if (_loaded && !force) return;

  const rawNodes = loadJsonFile('skill_tree_reconciled.json', []);
  _classes       = loadJsonFile('classes.json', { classes: {}, masteries: {}, passiveTreeByClass: {} });

  _trees = {};
  for (const { treeID, treeName, nodeID, nodeName, description, maxPoints, stats } of rawNodes) {
    if (!_trees[treeID]) _trees[treeID] = { name: treeName, nodes: {} };
    _trees[treeID].nodes[String(nodeID)] = { id: nodeID, nodeName, description, maxPoints, stats };
  }
  _passives = _trees;
  _skills   = _trees;

  _loaded = true;

  const treeCount = Object.keys(_trees).length;
  const nodeCount = rawNodes.length;
  console.log(`[db] Loaded: ${nodeCount} nodes across ${treeCount} trees (passives + skills)`);
}

/** @private */
function loadJsonFile(filename, fallback) {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) {
    console.warn(`[db] Missing: ${filePath} — run: python extractor/extract.py --nodes <path>`);
    return fallback;
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    console.error(`[db] Failed to parse ${filename}:`, e.message);
    return fallback;
  }
}

// ─── Passive queries ──────────────────────────────────────────────────────────

/**
 * Look up a passive node by classId + nodeId.
 * Resolves classId → treeID → node automatically.
 *
 * @param {number|string} classId  — e.g. 3 for Sentinel
 * @param {number|string} nodeId   — node id from Maxroll history[]
 * @returns {object|null}
 */
function getPassive(classId, nodeId) {
  const treeId = getPassiveTreeId(classId);
  if (!treeId) return null;
  return _passives[treeId]?.nodes?.[String(nodeId)] ?? null;
}

/**
 * Get the passive treeID for a given classId.
 * @param {number|string} classId
 * @returns {string|null}  e.g. "kn-1"
 */
function getPassiveTreeId(classId) {
  return _classes.passiveTreeByClass?.[String(classId)] ?? null;
}

/**
 * Get the passive tree name for a given classId.
 * @param {number|string} classId
 * @returns {string|null}  e.g. "Knight"
 */
function getPassiveTreeName(classId) {
  const treeId = getPassiveTreeId(classId);
  return treeId ? (_passives[treeId]?.name ?? null) : null;
}

// ─── Skill queries ────────────────────────────────────────────────────────────

/**
 * Look up a node within a skill tree.
 * skillKey = treeID from "Global Tree Data.json" = Maxroll skillTrees key.
 *
 * @param {string}        skillKey  — e.g. "es6ai"
 * @param {number|string} nodeId
 * @returns {object|null}
 */
function getSkillNode(skillKey, nodeId) {
  return _skills[skillKey]?.nodes?.[String(nodeId)] ?? null;
}

/**
 * Get the skill name for a given treeID/skillKey.
 * @param {string} skillKey
 * @returns {string|null}
 */
function getSkillName(skillKey) {
  return _skills[skillKey]?.name ?? null;
}

// ─── Class / mastery queries ──────────────────────────────────────────────────

/**
 * @param {number|string} classId
 * @returns {string|null}  e.g. "Sentinel"
 */
function getClassName(classId) {
  return _classes.classes?.[String(classId)] ?? null;
}

/**
 * Get a mastery name using the per-class relative mastery ID (1–3).
 * Maxroll JSON uses per-class relative IDs, NOT global sequential IDs.
 *
 * @param {number|string} classId   — e.g. 3 for Sentinel
 * @param {number|string} masteryId — per-class relative mastery ID (1–3)
 * @returns {string|null}  e.g. "Void Knight"
 */
function getMasteryName(classId, masteryId) {
  return _classes.masteriesByClass?.[String(classId)]?.[String(masteryId)] ?? null;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

/**
 * Return full raw DB (for passing to parser functions).
 */
function all() {
  return { passives: _trees, skills: _trees, classes: _classes };
}

/**
 * True if db/data files have been populated by extractor/extract.py.
 */
function isPopulated() {
  return Object.keys(_trees).length > 0;
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  load,
  getPassive,
  getPassiveTreeId,
  getPassiveTreeName,
  getSkillNode,
  getSkillName,
  getClassName,
  getMasteryName,
  all,
  isPopulated,
};
