/**
 * db/build-db.js
 * ───────────────
 * Loads and queries the static game data files in db/data/.
 * Generated by extractor/extract.py from "Global Tree Data.json".
 * Re-run extractor after each game patch.
 *
 * ─── Data Files ──────────────────────────────────────────────────────────────
 *
 *  db/data/skills.json   → { [treeID]: SkillTree }
 *  db/data/passives.json → { [treeID]: PassiveTree }
 *  db/data/classes.json  → { classes, masteries, passiveTreeByClass }
 *
 * ─── Real node shape (from Global Tree Data.json) ────────────────────────────
 * {
 *   id:                 number,   — node identifier used in Maxroll history[]
 *   name:               string,   — display name
 *   maxPoints:          number,   — max allocatable points (0 = root/connector)
 *   requiredMastery:    number,   — 0 = no mastery gate
 *   masteryRequirement: number,   — min points in mastery tree required
 *   requirements:       array,    — [{nodeID, requirement}] prerequisite nodes
 * }
 *
 * NOTE: There is NO description field. Descriptions are not in the source data.
 *
 * ─── Passive tree structure ───────────────────────────────────────────────────
 *
 *  passives.json is keyed by treeID (one per base class), NOT flat nodeId.
 *  This is because the same nodeId can exist in different class trees.
 *
 *  To look up a passive node you need classId → treeID → nodeId:
 *    db.getPassive(classId, nodeId)
 *
 *  classId → treeID mapping (from classes.json passiveTreeByClass):
 *    1 (Acolyte)   → "ac-1"
 *    2 (Mage)      → "mg-1"
 *    3 (Sentinel)  → "kn-1"
 *    4 (Rogue)     → "rg-1"
 *    5 (Primalist) → "pr-1"
 *
 * ─── treeID = Maxroll skillKey ───────────────────────────────────────────────
 *
 *  Skills are keyed by treeID which is the exact same key Maxroll uses.
 *  e.g. skills["es6ai"] = Erasing Strike, skills["v01cv"] = Void Cleave.
 *  No mapping step is needed.
 *
 * ─── Usage ───────────────────────────────────────────────────────────────────
 *
 *   const db = require('./build-db');
 *   db.load();
 *
 *   db.getPassive(3, 49)           // classId=3 (Sentinel), nodeId=49 → node | null
 *   db.getSkillNode('es6ai', 2)    // skillKey, nodeId → node | null
 *   db.getSkillName('es6ai')       // → "Erasing Strike" | null
 *   db.getPassiveTreeId(3)         // classId → "kn-1"
 *   db.getClassName(3)             // → "Sentinel" | null
 *   db.getMasteryName(7)           // → "Void Knight" | null
 *   db.all()                       // → { passives, skills, classes }
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, 'data');

// ─── Internal state ───────────────────────────────────────────────────────────

let _passives = {};   // { [treeID]: { name, nodes: { [id]: node } } }
let _skills   = {};   // { [treeID]: { name, nodes: { [id]: node } } }
let _classes  = { classes: {}, masteries: {}, passiveTreeByClass: {} };
let _loaded   = false;

// ─── Loader ───────────────────────────────────────────────────────────────────

/**
 * Load all data files into memory. Safe to call multiple times.
 * @param {boolean} [force=false]
 */
function load(force = false) {
  if (_loaded && !force) return;

  _passives = loadJsonFile('passives.json', {});
  _skills   = loadJsonFile('skills.json',   {});
  _classes  = loadJsonFile('classes.json',  { classes: {}, masteries: {}, passiveTreeByClass: {} });

  _loaded = true;

  const skillCount   = Object.keys(_skills).length;
  const passiveCount = Object.values(_passives).reduce((n, t) => n + Object.keys(t.nodes ?? {}).length, 0);
  console.log(`[db] Loaded: ${skillCount} skill trees, ${passiveCount} passive nodes across ${Object.keys(_passives).length} class trees`);
}

/** @private */
function loadJsonFile(filename, fallback) {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) {
    console.warn(`[db] Missing: ${filePath} — run: python extractor/extract.py`);
    return fallback;
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    console.error(`[db] Failed to parse ${filename}:`, e.message);
    return fallback;
  }
}

// ─── Passive queries ──────────────────────────────────────────────────────────

/**
 * Look up a passive node by classId + nodeId.
 * Resolves classId → treeID → node automatically.
 *
 * @param {number|string} classId  — e.g. 3 for Sentinel
 * @param {number|string} nodeId   — node id from Maxroll history[]
 * @returns {object|null}
 */
function getPassive(classId, nodeId) {
  const treeId = getPassiveTreeId(classId);
  if (!treeId) return null;
  return _passives[treeId]?.nodes?.[String(nodeId)] ?? null;
}

/**
 * Get the passive treeID for a given classId.
 * @param {number|string} classId
 * @returns {string|null}  e.g. "kn-1"
 */
function getPassiveTreeId(classId) {
  return _classes.passiveTreeByClass?.[String(classId)] ?? null;
}

/**
 * Get the passive tree name for a given classId.
 * @param {number|string} classId
 * @returns {string|null}  e.g. "Knight"
 */
function getPassiveTreeName(classId) {
  const treeId = getPassiveTreeId(classId);
  return treeId ? (_passives[treeId]?.name ?? null) : null;
}

// ─── Skill queries ────────────────────────────────────────────────────────────

/**
 * Look up a node within a skill tree.
 * skillKey = treeID from "Global Tree Data.json" = Maxroll skillTrees key.
 *
 * @param {string}        skillKey  — e.g. "es6ai"
 * @param {number|string} nodeId
 * @returns {object|null}
 */
function getSkillNode(skillKey, nodeId) {
  return _skills[skillKey]?.nodes?.[String(nodeId)] ?? null;
}

/**
 * Get the skill name for a given treeID/skillKey.
 * @param {string} skillKey
 * @returns {string|null}
 */
function getSkillName(skillKey) {
  return _skills[skillKey]?.name ?? null;
}

// ─── Class / mastery queries ──────────────────────────────────────────────────

/**
 * @param {number|string} classId
 * @returns {string|null}  e.g. "Sentinel"
 */
function getClassName(classId) {
  return _classes.classes?.[String(classId)] ?? null;
}

/**
 * @param {number|string} masteryId
 * @returns {string|null}  e.g. "Void Knight"
 */
function getMasteryName(masteryId) {
  return _classes.masteries?.[String(masteryId)]?.name ?? null;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

/**
 * Return full raw DB (for passing to parser functions).
 */
function all() {
  return { passives: _passives, skills: _skills, classes: _classes };
}

/**
 * True if db/data files have been populated by extractor/extract.py.
 */
function isPopulated() {
  return Object.keys(_skills).length > 0 || Object.keys(_passives).length > 0;
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  load,
  getPassive,
  getPassiveTreeId,
  getPassiveTreeName,
  getSkillNode,
  getSkillName,
  getClassName,
  getMasteryName,
  all,
  isPopulated,
};
